version: "3"
services:
  php8cookbook:
    container_name: php8cookbook
    hostname: php8cookbook
    image: unlikelysource/php8cookbook
    volumes:
     - ".:/repo"
    ports:
     - "8888:80"
    build: ./docker
    command: /tmp/startup.sh
    restart: always
    networks:
      php8cookbook_net:
        ipv4_address: 10.10.10.10
networks:
  php8cookbook_net:
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
