FROM docker.io/alpine:3.20
COPY nginx.default.conf /tmp/default.conf
RUN \
    echo "Installing basic utilities ..." && \
    apk add curl git bash nano
RUN \
    echo "Installing nginx ..." && \
    apk add nginx && \
    mv -f /etc/nginx/http.d/default.conf /etc/nginx/http.d/default.conf.old && \
    chown -R nginx /var/www
WORKDIR /repo
ENTRYPOINT /tmp/startup.sh
